Tran Cong Dat - 51800183

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('adult.data')
# print(df)
print(df.shape)
print(df.head)

(32560, 15)
<bound method NDFrame.head of        39          State-gov   77516    Bachelors   13        Never-married  \
0      50   Self-emp-not-inc   83311    Bachelors   13   Married-civ-spouse   
1      38            Private  215646      HS-grad    9             Divorced   
2      53            Private  234721         11th    7   Married-civ-spouse   
3      28            Private  338409    Bachelors   13   Married-civ-spouse   
4      37            Private  284582      Masters   14   Married-civ-spouse   
...    ..                ...     ...          ...  ...                  ...   
32555  27            Private  257302   Assoc-acdm   12   Married-civ-spouse   
32556  40            Private  154374      HS-grad    9   Married-civ-spouse   
32557  58            Private  151910      HS-grad    9              Widowed   
32558  22            Private  201490      HS-grad    9        Never-married   
32559  52       Self-emp-inc  287927      HS-grad    9   Married-civ-spouse   

         

In [5]:
x = df.values[:,:-1]
y = df.values[:,-1]
print(x.shape)
print(y.shape)

(32560, 14)
(32560,)


In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for i in range(x.shape[1]):
    x[:,i] = encoder.fit_transform(x[:,i])
print(x)

[[33 6 2925 ... 0 12 39]
 [21 4 14085 ... 0 39 39]
 [36 4 15335 ... 0 39 39]
 ...
 [41 4 7882 ... 0 39 39]
 [5 4 12880 ... 0 19 39]
 [35 5 17824 ... 0 39 39]]


In [10]:
x_train = x[:32558,:] # 32559
y_train = y[:32558]

x_test = x[32558:,:]
y_test = y[32558:,]

print(x_train)
print(y_train)

[[33 6 2925 ... 0 12 39]
 [21 4 14085 ... 0 39 39]
 [36 4 15335 ... 0 39 39]
 ...
 [10 4 16527 ... 0 37 39]
 [23 4 8079 ... 0 39 39]
 [41 4 7882 ... 0 39 39]]
[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' >50K' ' <=50K']


In [11]:
from sklearn.naive_bayes import CategoricalNB
model1 = CategoricalNB()
model1.fit(x_train, y_train)

y_pred = model1.predict(x_test)
print(y_pred)
# # print(y_test)

[' <=50K' ' >50K']


In [12]:
from sklearn.naive_bayes import GaussianNB
model3 = GaussianNB()
model3.fit(x_train, y_train)

y_pred = model3.predict(x_test)
print(y_pred)

[' <=50K' ' >50K']


In [13]:
from sklearn.naive_bayes import ComplementNB
model4 = ComplementNB()
model4.fit(x_train, y_train)

y_pred = model4.predict(x_test)
print(y_pred)

[' <=50K' ' >50K']
