In [3]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('computer.csv')
print(df)
print(df.shape)

       Age  Income Student Credit_rating  Buy
0     30<=    high      no          fair   no
1     30<=    high      no     excellent   no
2   31..40    high      no          fair  yes
3      40>  medium     yes          fair  yes
4      40>     low     yes          fair  yes
5      40>     low     yes     excellent   no
6   31..40     low      no     excellent  yes
7     30<=  medium      no          fair   no
8     30<=     low     yes          fair  yes
9      40>  medium     yes          fair  yes
10    30<=  medium     yes     excellent  yes
11  31..40  medium      no     excellent  yes
12  31..40    high     yes          fair  yes
13     40>  medium      no     excellent   no
(14, 5)


In [10]:
x = df.values[:,:-1]
y = df.values[:,-1]
print(x)
print(y)

[['30<=' 'high' 'no' 'fair']
 ['30<=' 'high' 'no' 'excellent']
 ['31..40' 'high' 'no' 'fair']
 ['40>' 'medium' 'yes' 'fair']
 ['40>' 'low' 'yes' 'fair']
 ['40>' 'low' 'yes' 'excellent']
 ['31..40' 'low' 'no' 'excellent']
 ['30<=' 'medium' 'no' 'fair']
 ['30<=' 'low' 'yes' 'fair']
 ['40>' 'medium' 'yes' 'fair']
 ['30<=' 'medium' 'yes' 'excellent']
 ['31..40' 'medium' 'no' 'excellent']
 ['31..40' 'high' 'yes' 'fair']
 ['40>' 'medium' 'no' 'excellent']]
['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'yes'
 'no']


In [12]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
for i in range(x.shape[1]):
    x[:,i] = encoder.fit_transform(x[:,i])
print(x)

[[0 0 0 1]
 [0 0 0 0]
 [1 0 0 1]
 [2 2 1 1]
 [2 1 1 1]
 [2 1 1 0]
 [1 1 0 0]
 [0 2 0 1]
 [0 1 1 1]
 [2 2 1 1]
 [0 2 1 0]
 [1 2 0 0]
 [1 0 1 1]
 [2 2 0 0]]


In [34]:
x_train = x[:12,:]
y_train = y[:12]
x_test = x[12:,:]
y_test = y[12:,]

print(x_train)
print(y_train)

[[0 0 0 1]
 [0 0 0 0]
 [1 0 0 1]
 [2 2 1 1]
 [2 1 1 1]
 [2 1 1 0]
 [1 1 0 0]
 [0 2 0 1]
 [0 1 1 1]
 [2 2 1 1]
 [0 2 1 0]
 [1 2 0 0]]
['no' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'yes']


In [32]:
from sklearn.naive_bayes import CategoricalNB
model1 = CategoricalNB()
model1.fit(x_train, y_train)

y_pred = model1.predict(x_test)
print(y_pred)
# print(y_test)

['yes' 'yes']


In [29]:
from sklearn.naive_bayes import MultinomialNB
model2 = MultinomialNB()
model2.fit(x_train, y_train)

y_pred = model2.predict(x_test)
print(y_pred)

['yes' 'yes']


In [30]:
from sklearn.naive_bayes import GaussianNB
model3 = GaussianNB()
model3.fit(x_train, y_train)

y_pred = model3.predict(x_test)
print(y_pred)

['yes' 'yes']


In [31]:
from sklearn.naive_bayes import ComplementNB
model4 = ComplementNB()
model4.fit(x_train, y_train)

y_pred = model4.predict(x_test)
print(y_pred)

['no' 'yes']
