In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
x = np.array([[1,2,3,4,5,6,7]])
y = np.array([[1,2,5.1,4.2,7.5,6.1,9.2]])

N = x1.shape[1]
x0 = np.ones((1,N))

X = np.concatenate((x0.T, x.T, y.T), axis=1)
d = X.shape[1]

# print(d)
print(X)

z = np.array([2,4.1,6.3,10.2,10.5,12.1,14.1])
print(z)

[[1.  1.  1. ]
 [1.  2.  2. ]
 [1.  3.  5.1]
 [1.  4.  4.2]
 [1.  5.  7.5]
 [1.  6.  6.1]
 [1.  7.  9.2]]
[ 2.   4.1  6.3 10.2 10.5 12.1 14.1]


In [12]:
# w : tham so
def f(x_i,w):
    return w[0]+w[1]*x_i

def loss(x,y,w):
    error = 0
    for i in range(len(x)):
        error += (y[i] - f(x[i], w))**2
    return error/(2*len(x))

# tinh dao ham tao diem w[0], w[1]
def derivative(x,y,w):
    d0 =0 #w[0]
    d1 =0 #w[1]
    for i in range(len(x)):
        d1 += x[i]*(f(x[i],w) - y[i])
        d0 = f(x[i],w) - y[i]
    return d0/len(x),d1/len(x)

In [25]:
epoch = 10
learning_rate = 0.01
w = [1,1]
loss_old = loss(x,y,w)

for i in range(epoch):
    
    a,b = derivative(x,y,w)
    w[0]  = w[0] - a*learning_rate
    w[1]  = w[1] - b*learning_rate    
    
#     Y = a+b*x[i]
    loss_new = loss(x,y,w)
    print('epoch_',i,':')
    print('w=',w)
    if abs(loss_new - loss_old) < 0.0001:
        break
    loss_old = loss_new

epoch_ 0 :
w= [array([0.99 , 0.99 , 1.011, 0.992, 1.015, 0.991, 1.012]), array([0.99 , 0.98 , 1.033, 0.968, 1.075, 0.946, 1.084])]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()