TRẦN CÔNG ĐẠT - 51800183

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
import math
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor

In [2]:
data = pd.read_csv('adult.data')
data.head(10)

39          State-gov   77516      Bachelors   13           Never-married  \
0  50   Self-emp-not-inc   83311      Bachelors   13      Married-civ-spouse   
1  38            Private  215646        HS-grad    9                Divorced   
2  53            Private  234721           11th    7      Married-civ-spouse   
3  28            Private  338409      Bachelors   13      Married-civ-spouse   
4  37            Private  284582        Masters   14      Married-civ-spouse   
5  49            Private  160187            9th    5   Married-spouse-absent   
6  52   Self-emp-not-inc  209642        HS-grad    9      Married-civ-spouse   
7  31            Private   45781        Masters   14           Never-married   
8  42            Private  159449      Bachelors   13      Married-civ-spouse   
9  37            Private  280464   Some-college   10      Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   
5       Other-service   Not-in-family   Black   Female      0   0   16   
6     Exec-managerial         Husband   White     Male      0   0   45   
7      Prof-specialty   Not-in-family   White   Female  14084   0   50   
8     Exec-managerial         Husband   White     Male   5178   0   40   
9     Exec-managerial         Husband   Black     Male      0   0   80   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K  
5         Jamaica   <=50K  
6   United-States    >50K  
7   United-States    >50K  
8   United-States    >50K  
9   United-States    >50K

In [9]:
df3 = pd.DataFrame({'Degree': ['Bachelors', 'HS-grad', '11th', 'Bachelors', 'Masters', '9th','Hs-grad','Masters','Bachelors','Some-college'],
                  'Sex': ['Male', 'Male','Male', 'Female','Female', 'Female','Male','Female','Male','Male'],
                   })
LE = LabelEncoder()
df3['code'] = LE.fit_transform(df3['Degree'])
print(df3)
#'Income':['<=50K','<=50K', '<=50K', '<=50K', '<=50K', '<=50K','>50K','>50K','>50K','>50K',]

         Degree     Sex  code
0     Bachelors    Male     2
1       HS-grad    Male     3
2          11th    Male     0
3     Bachelors  Female     2
4       Masters  Female     5
5           9th  Female     1
6       Hs-grad    Male     4
7       Masters  Female     5
8     Bachelors    Male     2
9  Some-college    Male     6


In [10]:
a = pd.get_dummies(df3['Degree']) 
print(a)

   11th  9th  Bachelors  HS-grad  Hs-grad  Masters  Some-college
0     0    0          1        0        0        0             0
1     0    0          0        1        0        0             0
2     1    0          0        0        0        0             0
3     0    0          1        0        0        0             0
4     0    0          0        0        0        1             0
5     0    1          0        0        0        0             0
6     0    0          0        0        1        0             0
7     0    0          0        0        0        1             0
8     0    0          1        0        0        0             0
9     0    0          0        0        0        0             1


In [11]:
b = pd.get_dummies(df3['Sex']) 
print(b)

   Female  Male
0       0     1
1       0     1
2       0     1
3       1     0
4       1     0
5       1     0
6       0     1
7       1     0
8       0     1
9       0     1


In [21]:
degree = np.array(a)
sex = np.array(b)
income = ['<=50K','<=50K', '<=50K', '<=50K', '<=50K', '<=50K','>50K','>50K','>50K','>50K']
# print(degree)
# print(sex)
# print(income)

In [ ]:
person_degree = [0,0,1,0,0,0,0] #Bachelor
person_sex = [0, 1] #male

In [23]:
degree = degree.T
print(degree.shape)

sex = sex.T
print(sex.shape)

(10, 7)
(10, 2)


In [25]:
X = np.concatenate((degree, sex), axis=1)
print(X)

[[0 0 1 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1 0]
 [0 1 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0 1]
 [0 0 0 0 0 1 0 1 0]
 [0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 1]]


In [27]:
model = KNeighborsClassifier(n_neighbors=3)
# training process
model.fit(X, income)

KNeighborsClassifier(n_neighbors=3)

In [30]:
X_test = np.array([[0,0,1,0,0,0,0, 0, 1]])
y_pred = model.predict(X_test)
print(y_pred)

['<=50K']


In [36]:
model2 = KNeighborsRegressor(n_neighbors=3)
# training process
model2.fit(X, degree)

KNeighborsRegressor(n_neighbors=3)

In [37]:
weight_pred = model2.predict(X_test)
print(weight_pred)

[[0.         0.         0.66666667 0.33333333 0.         0.
  0.        ]]
