In [6]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

refund = np.array(['y','n','n','y','n','n','y','n','n','n'])
status = np.array(['s','m','s','m','d','m','d','s','m','s'])
income = np.array([125,100,70,120,95,60,220,85,75,90])
label = np.array(['no','no','no','no','yes','no','no','yes','no','yes'])

encoder = LabelEncoder()
refund = encoder.fit_transform(refund)

encoder2 = LabelEncoder()
status = encoder.fit_transform(status)

# encoder = LabelEncoder()
# refund = encoder.fit_transform(income)
refund.T
print(refund.T)
print(status.T)
print(income.T)

# Y = np.concatenate((height,age), axis=1)
# print(Y)

minmax = MinMaxScaler()
Y = minmax.fit_transform(Y) #convert data to 0 - 1
print('Data Scaler :')
print(Y)

model = KNeighborsClassifier(n_neighbors=3)
# training process
model.fit(Y, label)

X_test = np.array([[5.5,38],[6.1,45]])
y_pred = model.predict(X_test)
print(y_pred)

[1 0 0 1 0 0 1 0 0 0]
[2 1 2 1 0 1 0 2 1 2]
[125 100  70 120  95  60 220  85  75  90]


NameError: name 'Y' is not defined