In [56]:
import numpy as np 
from numpy import random

In [24]:
# mang 1 chieu
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [18]:
# mang 2 chieu : 2 hang , 4 cot
arr2D = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2D)

[[1 2 3 4]
 [1 2 3 4]]


In [29]:
# mang 2 chieu lay tu mang (1)
arr2d = np.array([arr,arr])
print(arr2d)

[[1 2 3]
 [1 2 3]]


In [34]:
# mang 3 chieu voi shape [2,3,4]
arr3d = np.array([[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]])
print(arr3d)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [90]:
# Mảng 1 mờ có kích thước 10 và tất cả các giá trị là 1
x = np.array([1]*10)
print(x)

[1 1 1 1 1 1 1 1 1 1]


In [108]:
#tao 2 chieu mang so thuc co 2 hang 3 cot tu 5 - 19
x = random.rand(2,3)
print(x*50)

[[18.11758435 47.99446036  6.9929679 ]
 [35.131858   16.06983382  5.37740405]]


In [57]:
#tao 2 chieu mang so nguyen co 2 hang 3 cot tu 10 - 20
x = random.choice([10,11,12,13,14,15,16,17,18,19,20], size=(2,3))
print(x)

[[19 18 18]
 [16 12 17]]


In [74]:
# get col and row of 2-D array 
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print('get col:',A[0, 0:3]) 
print('get row:',A[0:3, 1])

[[1 2 3]
 [4 5 6]]
get col: [1 2 3]
get row: [2 5]


In [128]:
#create a 3-dim array and show its shape: call it B
B = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(B)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [129]:
#convert A to 1-dim array
B = A.reshape(-1)
print(B)

[1 2 3 4 5 6]


In [132]:
#convert A to 2-dim array with k rows 
C = A.reshape(3,2)
print(C)

[[1 2]
 [3 4]
 [5 6]]


In [135]:
#create an 1-dim array and convert it to 2-dim array with shape(m,n)
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [64]:
from numpy import random
x = random.randint(100, size=100)
print(x)
print('20 first elements:',x[:20])
print('20 last elements:',x[80:])

[ 7 72 59 68 95 20 21 60 22 82 45 23 22 65  7 50 98 50 71 30 92 46 73 79
 97 30 43 46 49 98 41 59 25 40 21 69 29 98 48 21 24 25 68 55 11 24  5 67
  1 56 14 52 14 74 20 30 53 36 88 68 18 32  7 64 84  2 49 54 61 41 21 16
 25 37  0  6 19 27 15 74 78 60 76 55 29 26 27 32 12 54 92 75  1 49 68 38
 40 63 81 14]
20 first elements: [ 7 72 59 68 95 20 21 60 22 82 45 23 22 65  7 50 98 50 71 30]
20 last elements: [78 60 76 55 29 26 27 32 12 54 92 75  1 49 68 38 40 63 81 14]


In [139]:
#get sub-array containing elements of index m to n
print(x[3:20])

[77  0 71  2  0 46 67 11 58 29 17 66 33 59 99  3 53]


In [39]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('Mang ban dau:',A)
b = np.delete(A,4,1)
print('mang da xoa:',b)


print(A[:2, 4:5])

Mang ban dau: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
mang da xoa: [[1 2 3 4]
 [6 7 8 9]]
[[ 5]
 [10]]


In [82]:
import numpy as geek
a = np.array([[1,1,1,1],[1,2,3,4]])
b = np.array([[2,2,2,2],[1,2,3,4]])

multi = geek.multiply(a, b)
print('nhan 2 ma tran :')
print(multi)
print('\n')
c = np.concatenate((a, b), axis=1)
print('concatenate by colums',c)
print('\n')
d = np.concatenate((a, b), axis=0)
print('concatenate by row',d)
# e = np.concatenate((a,b[0:3, 3]), axis=1)
# print(e)

nhan 2 ma tran :
[[ 2  2  2  2]
 [ 1  4  9 16]]


concatenate by colums [[1 1 1 1 2 2 2 2]
 [1 2 3 4 1 2 3 4]]


concatenate by row [[1 1 1 1]
 [1 2 3 4]
 [2 2 2 2]
 [1 2 3 4]]


In [22]:
# '''
# E. Operation with condition 
# 1) given an 1-dim array A = [1 2 3 5 7 4]
# - remove all odd numbers in A
# - get array B by removing elements so that their indexs of even numbers 
# 2) given two 1-dim arrays, 
# - get the intersection of them
# - get the union of them 
# '''


In [111]:
a = np.array([1,2,3,5,7,4])
b = [x for x in a if x%2==0]
print('remove all odd:',b)
print('\n')
c = []
for i in a:
    if i % 2 == 0:
        c.append(a[i])        
print('get even index: ',c)


remove all odd: [2, 4]


get even index:  [3, 7]


In [117]:
import numpy as geek 
a = np.array([1,2,3,5,7,4])
b = np.array([3,5,5,7,6,6])
inter = geek.intersect1d(a,b)
print('intersection of a and b:',inter)
print('\n')
uni = np.union1d(a,b)
print('uniono of a and b:',uni)

intersection of a and b: [3 5 7]


uniono of a and b: [1 2 3 4 5 6 7]
